### ISSUE TITLE
Caching unexpectedly disabled by Cache-Control: no-store

### ISSUE THREAD

**Issue by p4-k4** [JWCook/aiohttp-client-cache#91] opened 2021-08-30 09:55 UTC
### The problem
Seems to be no caching happening for certain URL strings, or as far as I can tell. (See below for reproduction code).

### Expected behavior
When using the URL string in the example (http://httpbin.org/delay/1), there's no issues. With the Facebook graph api URL shown below, expecting to see that `response.from_cache` is True.

### Steps to reproduce the behavior
```python async def main():
  async with CachedSession(cache=cache) as session:
    params = {'access_token': token}
    response = await session.get(f'https://graph.facebook.com/v11.0/0000000000000', params=params)
    print(response.from_cache, response.created_at, response.expires, response.is_expired)
    return await response.json()
```

Run twice, second run shows that the sqlite file has been created but we're not retrieving from cache.

### Environment
- aiohttp-client-cache version: [`0.4.3`]
- Python version: [`3.9`]
- Platform: [Ubuntu 20.04 on ARM]

**Comment by JWCook** [comment] 2021-08-30 14:43
That particular URL returns a `400 Bad Request`, or at least that's all I can get without an access token. By default only 200 responses are cached, but you can change that with the `allowed_codes` option:
```python
cache = SQLiteBackend(allowed_codes=[200, 400])
async with CachedSession(cache=cache) as session:
    params = {'access_token': token}
    response = await session.get(f'https://graph.facebook.com/v11.0/0000000000000', params=params)
    print(response.from_cache, response.created_at, response.expires, response.is_expired)
    return await response.json()
```

What kind of response do you get with your access token?

**Comment by p4-k4** [comment] 2021-08-30 18:08
Hey there.

Yeah of course we'd get a 404, there's no token or userid set with the example URL I provided. The example was just to show the formatting of URL and how I've split parameters.

I use the default config provided in the usage example so should be caching 200 responses as you mentioned. And it does, but just not URL's of this format for some reason.

The print statement on second run (and thereafter) returns results that the Client session is not using the cache.

Change the URL back to the URL you have on your usage example and everything's fine.

How is this lib supposed to be extracting keys to correspond the cache to? Does it take URL's/params/args into consideration? Any potential issues with that extraction process?

Thanks! This lib looks like a winner by the way, if only I could use my URLs 😅

**Comment by p4-k4** [comment] 2021-08-30 18:20
Forgot to mention sorry, I DO get 200 responses from this URL, of course with a correct userid and token.

So there's no issues making and retrieving the request. The issue is in the "caching" side.

**Comment by JWCook** [comment] 2021-08-30 18:36
> How is this lib supposed to be extracting keys to correspond the cache to? Does it take URL's/params/args into consideration?

Requests are matched based on the normalized URL, request params, request body, and optionally headers. And then there are a few conditions that will skip writing to the cache based on backend settings.

Since I can't test that particular endpoint myself, I'll need a little more info about what it's returning to figure out what's going on. Can you show me the response content, headers, history, and request_info with any sensitive information redacted?

Could you also test with the latest pre-release version (`pip install --pre aiohttp-client-cache`)? There are some unreleased changes to request matching, and it's possible one of them could fix your issue.

**Comment by JWCook** [comment] 2021-08-30 18:42
Ah, and one more thing: Since that `access_token` is going to change every time you refresh it, you won't want that to be part of the cache key that future requests will be matched against. You can use the `ignored_params` option for that:
```python
cache = SQLiteBackend(ignored_params=['access_token'])
```

**Comment by JWCook** [comment] 2021-08-30 18:43
I've documented request matching behavior more thoroughly over in the reuqests-cache docs: https://requests-cache.readthedocs.io/en/latest/user_guide/matching.html

Although there are a few differences, mainly that aiohttp-client-cache doesn't yet support custom request matching.

**Comment by p4-k4** [comment] 2021-08-30 19:14
Cheers for that, yeah certainly not caching the `access_token`. I already had that added to `ignored_params`.

Here is the response I am getting(200 status). I won't show the json data though, all of it is private info.

Sorry but how do I get the headers from `CacheSession`? This just throws an exception.
```python
print(response.headers())
```

Here's the response.

**Response**
`<CIMultiDictProxy('Etag': '"2755b5b47791d26509cb261c63a6801dc43b7d4d"', 'Content-Type': 'application/json; charset=UTF-8', 'Vary': 'Origin', 'x-business-use-case-usage': '{"106676908248064":[{"type":"messenger","call_count":1,"total_cputime":1,"total_time":1,"estimated_time_to_regain_access":0}]}', 'x-fb-rlafr': '0', 'Access-Control-Allow-Origin': '*', 'facebook-api-version': 'v11.0', 'Strict-Transport-Security': 'max-age=15552000; preload', 'Pragma': 'no-cache', 'Cache-Control': 'private, no-cache, no-store, must-revalidate', 'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT', 'x-fb-request-id': 'ArMLghGFUsqHdSRNpa0wx3Z', 'x-fb-trace-id': 'DK+D9wlzgVO', 'x-fb-rev': '1004326406', 'X-FB-Debug': 'ZvZ+3ZeyjyU1hxrkDq2ccCFeoMsOhE5kljlENXzqfQ4ZgnsEkbpBBrpeD+oTlDnk+gIbhQnOYbCk1F4xXKAoow==', 'Date': 'Mon, 30 Aug 2021 19:07:08 GMT', 'Priority': 'u=3,i', 'Alt-Svc': 'h3-29=":443"; ma=3600,h3-27=":443"; ma=3600', 'Connection': 'keep-alive', 'Content-Length': '221')>`

**Cache**
```python
print(response.from_cache, response.created_at, response.expires, response.is_expired)
```
**Output**
`False None None False`

**Comment by JWCook** [comment] 2021-08-30 20:05
Aha! That response includes `Cache-Control: no-store`, which tells the cache to not save that response... but that is **not** supposed to be enabled by default, only if you use `cache_control=True` 🤦‍♂️. Sorry about that!

That will be fixed shortly.

**Comment by p4-k4** [comment] 2021-08-30 20:10
Awesome! Really looking forward to using this - I had explored other caching options but were super fiddly and didn't quite go to the extent of this library offering support for multiple backends etc. Docs look great too! Keep up the good work.

**Comment by JWCook** [comment] 2021-08-30 20:12
Fixed in the latest pre-release build (`0.5.0b1`). Give that a try and let me know if that works for you.

I also added a bit more logging, so if you see more unexpected behavior in the future, enable `DEBUG` logging for aiohttp_client_cache (and maybe just `INFO` logging for everything else, since aiohttp debug logs are a bit verbose):
```python
import logging
logging.basicConfig(level='INFO')
logging.getLogger('aiohttp_client_cache').setLevel('DEBUG')
```

And you'll see info for why each request was or wasn't cached, for example:
```python
{
    'disabled cache': False,
    'disabled method': False,
    'disabled status': False,
    'disabled by filter': False,
    'disabled by headers or expiration params': False,
    'expired': False,
}
```

**Comment by p4-k4** [comment] 2021-08-30 20:13
> Fixed in the latest pre-release build (`0.5.0b1`). Give that a try and let me know if that works for you.
> 
> I also added a bit more logging, so if you see more unexpected behavior in the future, enable `DEBUG` logging for aiohttp_client_cache (and maybe just `INFO` logging for everything else, since aiohttp debug logs are a bit verbose):
> 
> ```python
> import logging
> logging.basicConfig(level='INFO')
> logging.getLogger('aiohttp_client_cache').setLevel('DEBUG')
> ```
> 
> And you'll see info for why each request was or wasn't cached, for example:
> 
> ```python
> {
>     'disabled cache': False,
>     'disabled method': False,
>     'disabled status': False,
>     'disabled by filter': False,
>     'disabled by headers or expiration params': False,
>     'expired': False,
> }
> ```

Cheers mate!

**Comment by JWCook** [comment] 2021-08-30 20:15
> Awesome! Really looking forward to using this - I had explored other caching options but were super fiddly and didn't quite go to the extent of this library offering support for multiple backends etc. Docs look great too! Keep up the good work.

Thanks, I appreciate it! And I know what you mean; before I started working on this, I was just really surprised that something like this library didn't already exist.

It's still pretty new, so any more bug reports or feedback in the future would be appreciated.

**Comment by p4-k4** [comment] 2021-08-30 20:21
I'd love to see an offering of a **general-use variant** of this library (not request specific) in the future. Might have a play when I get some time but yep, this lib has saved my ass quite a lot. Will post back if any other issues found.

**Comment by JWCook** [comment] 2021-08-30 21:08
That might be doable. All the backend-specific operations are wrapped in [this interface](https://github.com/JWCook/aiohttp-client-cache/blob/main/aiohttp_client_cache/backends/base.py#L238-L324). That just behaves like a generic collection, not specific to HTTP requests, so the subclasses of that could potentially be moved to a separate library.

Have you checked out [aiocache](https://github.com/aio-libs/aiocache)? I haven't used it myself, but it looks fairly extensible. I briefly considered refactoring this library to build on top of that, but I was already familiar with requests-cache so that was an easier starting point for me.

If you wanted that but with SQLite, for example, [SQLiteCache](https://github.com/JWCook/aiohttp-client-cache/blob/dac212424968c01860b501470969b12401454bdb/aiohttp_client_cache/backends/sqlite.py#L38) from this library could probably be refactored into a backend for aiocache.

**Closed** 2021-08-31 02:32 UTC
Labels: bug
