### ISSUE TITLE
AttributeError: 'CachedResponse' object has no attribute 'content_type'

### ISSUE THREAD

**Issue by AndreyMZ** [JWCook/aiohttp-client-cache#117] opened 2022-05-12 11:01 UTC
### The problem
`CachedResponse` object has no property `content_type`.

### Expected behavior
`CachedResponse` object has property `content_type` like `ClientResponse` does.

### Steps to reproduce the behavior
Something like:
~~~py
from aiohttp_client_cache import CachedSession

async with CachedSession() as session:
    async with session.get("https://example.com/") as response:
        content_type = response.content_type
~~~

### Environment
- aiohttp-client-cache version: `0.6.1`
- Python version: `3.9`
- Platform: Windows 10

**Comment by AIGeneratedUsername** [comment] 2022-05-12 11:14
I've tried to run your code snippet and the `content_type` attribute seems to be available.
```python
import asyncio

from aiohttp_client_cache import CachedSession

async def main():
    async with CachedSession() as session:
        async with session.get("https://example.com/") as response:
            content_type = response.content_type
            print(f"content_type: {content_type}")   # prints `content_type: text/html`

asyncio.run(main())
```

**Comment by AIGeneratedUsername** [comment] 2022-05-12 11:29
Since you did not provide a reproducible code sample, I am trying to understand what is your use case. Are you trying to get a `CachedResponse` from a backend manually?

**Comment by JWCook** [comment] 2022-05-12 14:49
I'm able to reproduce it. `CachedSession` without a `backend` argument uses a non-persistent memory backend by default, so that example will always create a new session and return the original response.

This will return a cached response and fail:
```python
async with CachedSession() as session:
    async with session.get("https://example.com/") as response:
        content_type = response.content_type
    async with session.get("https://example.com/") as response:
        content_type = response.content_type
```

It looks like `CachedResponse` is missing the properties from [HeadersMixin](https://github.com/aio-libs/aiohttp/blob/e16fb6225ec7f2fe190e63ff20a439cc20182713/aiohttp/helpers.py#L734), including content_type. I'll fix that.

**Comment by JWCook** [comment] 2022-05-13 13:51
Fixed in `main`. Thanks for the bug report!

**Closed** 2022-05-13 13:51 UTC
Labels: bug
