### ISSUE TITLE
Still creating network traffic when using cached responses

### ISSUE THREAD

**Issue by willsigg** [JWCook/aiohttp-client-cache#24] opened 2021-02-25 01:30 UTC
so i have tried to cache the data that my python script requests, but it doesnt seem to be working. wireshark and task manager both say that python is still requesting data even though the URL is the same. here is my old code:

`async with aiohttp.ClientSession() as session:

            async with session.get(leaderboard_url) as res:

                leaderboard_json = await res.json(encoding='utf-8-sig')`

and this is how i have dropped in this project:

`async with aiohttp_client_cache.CachedSession() as session:

            async with session.get(leaderboard_url) as res:

                leaderboard_json = await res.json(encoding='utf-8-sig')`
				
here is what i have imported: `import aiohttp_client_cache`

and then i also started the cache with `session = aiohttp_client_cache.CachedSession()`

do you know why this is not caching my requests? i have tried using sqlite instead of memory, but that doesnt seem to work.

**Comment by JWCook** [comment] 2021-02-25 01:49
I'll look into it. There is a good chance that I broke something recently. Like the Readme says, this project is very early in development!

**Comment by JWCook** [comment] 2021-02-25 02:46
I'm not able to reproduce this locally. Can you post a complete code example?

And can you show me the output of this example:
```python
import asyncio
import aiohttp_client_cache

async def cache_test():
    from aiohttp_client_cache import CachedSession, SQLiteBackend

    async with CachedSession(cache=SQLiteBackend()) as session:
        for i in range(10):
            response = await session.get('http://httpbin.org/delay/1')
            print(f'Response {i}:', type(response).__name__)
        cached_responses = await session.cache.responses.values()
        print('Cached responses:', len(cached_responses))

asyncio.run(cache_test())
```

**Comment by willsigg** [comment] 2021-02-25 03:09
`Traceback (most recent call last):
  File "C:\Users\Will Sigg\Downloads\ghostdatabase\cachetest.py", line 12, in <module>
    asyncio.run(cache_test())
  File "C:\Users\Will Sigg\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Will Sigg\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Will Sigg\Downloads\ghostdatabase\cachetest.py", line 5, in cache_test
    async with CachedSession(cache=SQLiteBackend()) as session:
TypeError: 'NoneType' object is not callable
[Finished in 0.6s]``

**Comment by willsigg** [comment] 2021-02-25 03:10
and to confirm: i am running 0.1.4

**Comment by JWCook** [comment] 2021-02-25 03:13
SQLiteBackend requires aiosqlite. I could probably make a better error message for that when a dependency is missing.

Can you `pip install aiosqlite` (or `pip install aiohttp-client-cache[backends]` to get all optional dependencies) and try again?

**Comment by JWCook** [comment] 2021-02-25 03:14
And here's an updated example that will detect how many times `aiohttp.ClientSession._request` actually gets called:

```python
import asyncio
from aiohttp import ClientSession
from aiohttp_client_cache import CachedSession, CachedResponse, SQLiteBackend
from unittest.mock import patch

mock_response = CachedResponse('GET', None, 200, None, None)

@patch.object(ClientSession, '_request', side_effect=[mock_response])
async def cache_test(mock_request):
    async with CachedSession(cache=SQLiteBackend()) as session:
        for i in range(10):
            response = await session.get('http://httpbin.org/delay/3')
            print(f'Response {i}:', type(response).__name__)
        cached_responses = await session.cache.responses.values()
        print('Cached responses:', len(cached_responses))
    print(f'Real ClientSession._request() called {mock_request.call_count} times')

asyncio.run(cache_test())
```

**Comment by willsigg** [comment] 2021-02-25 03:41
odd, that example you sent works, but task manager shows that my script is still using the network.

**Comment by JWCook** [comment] 2021-02-25 03:48
Huh, well that's curious! With `aiohttp.ClientSession._request` mocked out, I'm not sure what would be creating network traffic. I don't have experience using Wireshark (although it's on my list of stuff to learn); would that be able to tell you what host(s) it's hitting and total bytes transferred?

**Comment by JWCook** [comment] 2021-03-01 01:47
I tested this against a local Flask server, and it only hit the endpoint once. You can try it yourself with the [Flask quickstart app](https://flask.palletsprojects.com/en/1.1.x/quickstart/), and run the [first example](https://github.com/JWCook/aiohttp-client-cache/issues/24#issuecomment-785535764) above against `http://localhost:5000/`, and it should log only one request.

Whatever that network traffic is that you're seeing, it doesn't seem to be the result of fetching a response more than once. Let me know if you can get more details with Wireshark.

**Comment by willsigg** [comment] 2021-03-01 02:01
I'll take another look at it. If you want, I can send some examples of how I init the cache in my scripts. I did check again today and it did still use the network so I have no idea why I cannot get it to work.

**Comment by JWCook** [comment] 2021-04-16 17:25
@willsigg It's possible what you're seeing is just `aiosqlite` connections to the SQLite db. Using `strace` shows a bunch of `EAGAIN (Resource temporarily unavailable)` messages for each cache operation, maybe a result of `aioslite` requesting non-blocking file operations. I will admit, though, that those low-level system calls are a bit over my head. I attached `strace` output both with and without SQLite, so you can see the difference:
* [strace with SQLite cache](https://github.com/JWCook/aiohttp-client-cache/files/6326849/sqlite_cache_strace.txt)
* [strace with non-persistent cache](https://github.com/JWCook/aiohttp-client-cache/files/6326850/dict_cache_strace.txt)

One way or another, it clearly shows that only one real HTTP request is made to httpbin.org.

**Closed** 2021-05-06 19:11 UTC
Labels: bug
